GET http://localhost:4000/clubs/
###
POST http://localhost:4000/clubs/createClub
Content-Type: application/json

{
    "clubId":"nss",
    "clubName":"NSS - VNRVJIET",
    "volunteers":[],
    "clubMembers":[],
    "gallery":[],
    "description":[
        {
            "type":"p",
            "value":"welcome to NSS"
        },
        {
            "type":"p",
            "value":"NSS is a professional student club"
        },
        {
            "type":"p",
            "value":"NSS is VNR,s most valuable club."
        },
        {
            "type":"p",
            "value":"It is a family of 10,000+ students."
        }
    ],
    "motto":[],
    "profilePic":"",
    "email":"",
    "data1":{},
    "password":"123"
}
###
POST http://localhost:4000/clubs/createAPost
Content-Type: application/json

{
    "subject":"MEGA BLOOD DONATION CAMP(MBDC)",
    "clubId":"nss",
    "clubName":"NSS",
    "active":true,
    "description":[
        {
            "type":"p",
            "value":"this is VNR's valuable event."
        },
        {
            "type":"p",
            "value":"this blood is donated to thalasemia patients"
        },
        {
            "type":"p",
            "value":"venue is at PG block seminar HALL"
        }
    ],
    "posters":[],
    "links":[
        {
            "name1":"google form registration link",
            "value1":"link here"
        }
    ],
    "lastDate":"10/06/2024",
    "contactDetails":[
        {
            "name":"goutham reddy",
            "phone":"9398141936",
            "email":"uppinurigouthamreddy@gmail.com"
        }
    ]
}
###
POST http://localhost:4000/clubs/getClubData
Content-Type: application/json

{
    "clubId":"nss"
}
###
POST http://localhost:4000/clubs/getClubPosts
Content-Type: application/json

{
    "clubId":"nss"
}
###
POST http://localhost:4000/clubs/checkCredentials
Content-Type: application/json

{
    "clubId":"nssd",
    "password":"13"
}

###
POST http://localhost:4000/clubs/getClubName
Content-Type: application/json

{
    "clubId":"nss"
}